export const DEFAULT_TEMPERATURE = "0°C";
export const UNKNOWN_WEATHER_CODE = 100;

export const weatherDescriptions = {
  0: "Clear sky ☀️",
  1: "Mainly clear 🌤️",
  2: "Partly cloudy 🌥️",
  3: "Overcast ☁️",
  45: "Fog 🌫️",
  48: "Depositing rime fog 🌫️",
  51: "Light drizzle 🌧️",
  53: "Moderate drizzle 🌧️",
  55: "Dense drizzle 🌧️",
  61: "Light rain 🌧️",
  63: "Moderate rain 🌧️",
  65: "Heavy rain 🌧️",
  66: "Light freezing rain ❄️",
  67: "Heavy freezing rain ❄️",
  71: "Light snow ❄️",
  73: "Moderate snow ❄️",
  75: "Heavy snow ❄️",
  77: "Snow grains ❄️",
  80: "Light rain showers 🌦️",
  81: "Moderate rain showers 🌧️",
  82: "Violent rain showers ⛈️",
  85: "Light snow showers 🌨️",
  86: "Heavy snow showers 🌨️",
  95: "Thunderstorm ⚡",
  96: "Thunderstorm with light hail ⛈️",
  99: "Thunderstorm with heavy hail ⛈️⚡",
  [UNKNOWN_WEATHER_CODE]: "Unknown weather 🤷‍♂️",
};
